### ISSUE TITLE
add ability to normalize plotted series so they can appear on the same scale

### ISSUE THREAD

**Issue by wesley-murray** [harrisonmg/jfplot#2]
Often when I use jfplot I am looking at multiple series at once so I can more easily get a handle on the story (series of events) that multiple data sources contribute to. In this case the shapes are more important than the specific values. The problem is right now, is that the auto scaling of these series prevents me from actually overlapping them on one screen.

I would like to propose a normalize checkbox that will take all the series being plotted and force them to be same scale. Maybe 0-1, 0-100, it does not actually matter. This may go without saying but for categorical data I would appreciate keeping the same order as displayed and also scale the representative numbers to match the original spacing. For example if I scale from 0 to 1, 3 categories would be assigned 0, 0.5, and 1; 5 categories would be 0, 0.25, 0.5, 0.75, 1.

**Comment by harrisonmg** [comment]
I've thought about this a bit, and I think automatic normalization may be a bit too specific of a feature. Would the issue be solved by supporting subplots with shared axes? Check out the "Subplots with Shared X-Axes" example from [this page](https://plotly.com/python/subplots/). I think that might be more broadly useful.

**Comment by harrisonmg** [comment]
Added subplots with 58ce290
